### ISSUE TITLE
Hashlinks get replaced with full URLs, breaking some subreddit CSS

### ISSUE THREAD

**Issue by t2t2** [haackr/no-np#1]
If a subreddit uses hash links to for example show images with css, this data gets lost when the extension fixes links (href="#whatever" gets replaced with href="http://reddit.....#whatever").

Examples:

https://www.reddit.com/r/leagueoflegends/wiki/comment-faces

https://www.reddit.com/r/leagueoflegends/comments/48ro5r/rox_tigers_vs_longzhu_gaming_lck_champions_2016/ (in front of character names)

**Comment by haackr** [comment]
Thanks @t2t2! I believe I've fixed the issue. If you are using the addon in chrome, it should update shortly if it hasn't already.  If you are using it in firefox, the update still has to be approved which will probably happen later today or sometime tomorrow.

**Comment by t2t2** [comment]
Update landed in firefox, yep works great now. :+1:
